apiVersion: v1
kind: Service
metadata:
  name: financemanagement-api-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: financemanagement-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
